In [1]:
import time

import pandas as pd 
import numpy as np
import seaborn as sns
from scipy import stats
import matplotlib.pyplot as plt

import imblearn
from imblearn.over_sampling import SMOTE 
from imblearn.pipeline import make_pipeline

import sklearn
from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedShuffleSplit, StratifiedKFold
from sklearn import neighbors, svm, tree, linear_model, ensemble, neural_network, metrics
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import roc_auc_score, confusion_matrix, roc_curve, auc, accuracy_score, precision_recall_curve, average_precision_score, cohen_kappa_score,\
classification_report, log_loss
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from imblearn.pipeline import Pipeline 
#########################################################################

%matplotlib inline
pd.set_option("max_columns",90, "max_rows", 90)

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
raw_df = pd.read_csv('Gse_panel_current_sample_raw.csv')

In [3]:
raw_df.head()

,loan_id,orig_chn,orig_rt,orig_upb,oltv,num_bo,dti,loan_purp,prop_type,num_unit,occ_stat,prop_state,msa,fico,oyr,oqtr,ind_ede,pmms_o,avg_upb,OUPB_Rel,fhb_flag,loan_age_qtr,year,qtr,status,status_prev,PMMS,HPI_O,HPI,ur,CUPB_calc,Orig_value,CLTV
0,F100Q1057907,T,8.00,65000,41,2.0,24,P,SF,1.0,O,WI,33340.0,752,2000,1,0.006619,8.26,124597.46950,0.521680,N,2,2000,3,Current,Current,8.03,156.42,161.16,4.000000,64866.87370,158536.58540,39.712615
1,F100Q1045595,T,8.25,81000,67,1.0,31,P,CO,1.0,O,IL,16974.0,787,2000,1,0.006619,8.26,144321.44180,0.561247,N,5,2001,2,Current,Current,7.13,140.68,156.12,4.400000,80348.95986,120895.52240,59.893918
2,8.32073E+11,C,8.25,148000,80,2.0,51,P,SF,1.0,P,WI,33340.0,733,2000,1,0.006619,8.26,124597.46950,1.187825,N,4,2001,1,Current,Current,7.01,156.42,166.05,4.230000,147117.00180,185000.00000,74.864766
3,F100Q1132127,R,8.75,94000,63,2.0,24,N,SF,1.0,O,MI,NaN,781,2000,1,0.006619,8.26,121230.93190,0.775380,N,2,2000,3,Current,Current,8.03,166.37,171.77,4.000000,93834.43235,149206.34920,60.911968
4,F100Q1027118,R,8.00,60000,61,2.0,28,P,SF,1.0,O,OH,45780.0,782,2000,1,0.006619,8.26,99538.46154,0.602782,N,10,2002,3,Current,Current,6.29,144.24,157.62,6.555973,58801.29455,98360.65574,54.066644